### ISSUE TITLE
Update the versions listed on the site

### ISSUE THREAD

**Issue by Kaffeine** [TelepathyIM/telepathy-www#3]
The versions listed on the site are outdated (we had a number of releases).

E.g.: https://github.com/TelepathyIM/telepathy-haze/pull/1#issuecomment-732138218

**Comment by Arusekk** [comment]
For reference:
https://github.com/TelepathyIM/telepathy-www/blob/5dd1eb581c4c6651d97674e217665e629df1fbf3/data/components.toml#L145
As opposed to the actual releases file listing: https://telepathy.freedesktop.org/releases/telepathy-haze/

**Comment by Kaffeine** [comment]
The `components.toml` was the easiest part of the job. :smile: 
The last time site updated with hugo-0.16 and the current release is [hugo-0.79](https://gohugo.io/) :facepalm: .
`apt install` installed `0.68` and I spent days to figure out what is going on and how to re-build the site correctly.
I hope I did it right.
